#!/usr/bin/env node
// This file is auto-generated by @lark-apaas/fullstack-cli

const { nodeFileTrace } = require('@vercel/nft');
const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');

try {
  require('dotenv').config({ path: path.join(ROOT_DIR, '.env') });
} catch {}
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const DIST_SERVER_DIR = path.join(DIST_DIR, 'server');
const ROOT_PACKAGE_JSON = path.join(ROOT_DIR, 'package.json');
const ROOT_NODE_MODULES = path.join(ROOT_DIR, 'node_modules');
const OUT_NODE_MODULES = path.join(DIST_DIR, 'node_modules');
const OUT_PACKAGE_JSON = path.join(DIST_DIR, 'package.json');

const SERVER_ENTRY = path.join(DIST_SERVER_DIR, 'main.js');

let SOURCE_ROOT = 'server';
try {
  const nestCli = JSON.parse(fs.readFileSync(path.join(ROOT_DIR, 'nest-cli.json'), 'utf8'));
  if (nestCli.sourceRoot) SOURCE_ROOT = nestCli.sourceRoot;
} catch {}
const SRC_TO_OUT_EXT = { '.mts': '.mjs', '.cts': '.cjs', '.ts': '.js' };

const RUNTIME_ENTRIES = (process.env.MIAODA_RUNTIME_ENTRIES || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)
  .map((srcRel) => {
    const fromSrc = path.relative(SOURCE_ROOT, srcRel);
    const ext = path.extname(fromSrc);
    const outRel = SRC_TO_OUT_EXT[ext] ? fromSrc.slice(0, -ext.length) + SRC_TO_OUT_EXT[ext] : fromSrc;
    return path.join(DIST_SERVER_DIR, outRel);
  })
  .filter((p) => {
    if (fs.existsSync(p)) return true;
    console.warn(`⚠️  MIAODA_RUNTIME_ENTRIES 入口在构建产物中不存在，已忽略: ${path.relative(ROOT_DIR, p)}`);
    return false;
  });

const BUILTIN_MODULES = new Set([
  'assert', 'buffer', 'child_process', 'cluster', 'crypto', 'dgram', 'dns',
  'events', 'fs', 'http', 'http2', 'https', 'net', 'os', 'path', 'stream',
  'string_decoder', 'timers', 'tls', 'url', 'util', 'v8', 'vm', 'zlib',
  'async_hooks', 'perf_hooks', 'worker_threads', 'inspector', 'trace_events'
]);

const nodeModulesSep = 'node_modules' + path.sep;
function extractPackageName(filePath) {
  const idx = filePath.lastIndexOf(nodeModulesSep);
  if (idx === -1) return null;

  const afterNodeModules = filePath.slice(idx + nodeModulesSep.length);
  const slashIdx = afterNodeModules.indexOf(path.sep);

  if (afterNodeModules[0] === '@') {
    const secondSlash = afterNodeModules.indexOf(path.sep, slashIdx + 1);
    return secondSlash === -1
      ? afterNodeModules
      : afterNodeModules.slice(0, secondSlash);
  }

  return slashIdx === -1 ? afterNodeModules : afterNodeModules.slice(0, slashIdx);
}

function removeDir(dir) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function copyDir(src, dest, stats = { hardLinks: 0, copies: 0 }) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath, stats);
    } else {
      try {
        fs.linkSync(srcPath, destPath);
        stats.hardLinks++;
      } catch {
        fs.copyFileSync(srcPath, destPath);
        stats.copies++;
      }
    }
  }

  return stats;
}

function copyPackagesSelectively(packages, rootNodeModules, outNodeModules) {
  const copiedCount = { success: 0, failed: 0 };
  const fileStats = { hardLinks: 0, copies: 0 };

  if (fs.existsSync(outNodeModules)) {
    removeDir(outNodeModules);
  }
  fs.mkdirSync(outNodeModules, { recursive: true });

  for (const pkg of packages) {
    const srcPath = path.join(rootNodeModules, pkg);
    const destPath = path.join(outNodeModules, pkg);

    if (!fs.existsSync(srcPath)) {
      copiedCount.failed++;
      continue;
    }

    try {
      const destDir = path.dirname(destPath);
      if (!fs.existsSync(destDir)) {
        fs.mkdirSync(destDir, { recursive: true });
      }

      copyDir(srcPath, destPath, fileStats);
      copiedCount.success++;
    } catch (err) {
      console.error(`   ⚠️  复制失败: ${pkg} - ${err.message}`);
      copiedCount.failed++;
    }
  }

  return { copiedCount, fileStats };
}

async function smartPrune() {
  console.log('🔍 开始智能依赖分析...\n');

  const totalStartTime = Date.now();

  if (!fs.existsSync(SERVER_ENTRY)) {
    console.error(`❌ 入口文件不存在: ${SERVER_ENTRY}`);
    console.error('   请先运行 npm run build:server');
    process.exit(1);
  }

  console.log(`📂 分析入口文件: ${path.relative(ROOT_DIR, SERVER_ENTRY)}`);
  if (RUNTIME_ENTRIES.length) {
    console.log(`📎 额外 trace 入口 (${RUNTIME_ENTRIES.length}): ${RUNTIME_ENTRIES.map((p) => path.relative(DIST_SERVER_DIR, p)).join(', ')}`);
  }

  console.log('🔎 追踪实际依赖...');
  const analyzeStart = Date.now();

  const { fileList } = await nodeFileTrace([SERVER_ENTRY, ...RUNTIME_ENTRIES], {
    base: ROOT_DIR,
    processCwd: ROOT_DIR,
    ts: false,
    conditions: ['node', 'production'],
    exportsOnly: true,
    analysis: {
      emitGlobs: false,
      computeFileReferences: false,
      evaluatePureExpressions: false,
    },
  });

  const analyzeElapsed = Date.now() - analyzeStart;
  console.log(`   ✅ 分析完成，耗时: ${analyzeElapsed}ms\n`);

  const requiredPackages = new Set();

  for (const file of fileList) {
    if (!file.includes('node_modules')) continue;

    const pkgName = extractPackageName(file);
    if (pkgName && !BUILTIN_MODULES.has(pkgName)) {
      requiredPackages.add(pkgName);
    }
  }

  console.log(`📦 静态分析需要 ${requiredPackages.size} 个 npm 包`);

  const originalPackage = JSON.parse(fs.readFileSync(ROOT_PACKAGE_JSON, 'utf8'));

  let addedSubDeps = 0;
  const visited = new Set();
  const queue = [...requiredPackages];

  while (queue.length > 0) {
    const depName = queue.shift();

    if (visited.has(depName)) continue;
    visited.add(depName);

    const depPkgPath = path.join(ROOT_NODE_MODULES, depName, 'package.json');
    if (!fs.existsSync(depPkgPath)) continue;

    try {
      const depPkg = JSON.parse(fs.readFileSync(depPkgPath, 'utf8'));
      const subDeps = {
        ...depPkg.dependencies,
        ...depPkg.optionalDependencies,
      };

      for (const subDep of Object.keys(subDeps)) {
        const subDepPath = path.join(ROOT_NODE_MODULES, subDep);
        if (!fs.existsSync(subDepPath)) continue;

        if (!requiredPackages.has(subDep)) {
          requiredPackages.add(subDep);
          addedSubDeps++;
        }

        if (!visited.has(subDep)) {
          queue.push(subDep);
        }
      }
    } catch {}
  }

  if (addedSubDeps > 0) {
    console.log(`📦 递归补充动态依赖，新增 ${addedSubDeps} 个包`);
  }

  const actionPlugins = originalPackage.actionPlugins || {};
  const actionPluginNames = Object.keys(actionPlugins);

  if (actionPluginNames.length > 0) {
    console.log(`🔌 发现 ${actionPluginNames.length} 个 Action 插件，添加到依赖列表...`);

    for (const pluginName of actionPluginNames) {
      requiredPackages.add(pluginName);

      const pluginPkgPath = path.join(ROOT_NODE_MODULES, pluginName, 'package.json');
      if (fs.existsSync(pluginPkgPath)) {
        try {
          const pluginPkg = JSON.parse(fs.readFileSync(pluginPkgPath, 'utf8'));
          if (pluginPkg.peerDependencies) {
            for (const peerDep of Object.keys(pluginPkg.peerDependencies)) {
              requiredPackages.add(peerDep);
            }
          }
        } catch {}
      }
    }

    console.log(`   ✅ 插件: ${actionPluginNames.join(', ')}`);
  }

  console.log(`📦 总共需要 ${requiredPackages.size} 个 npm 包\n`);

  console.log('📋 选择性复制 node_modules（仅复制需要的包）...');
  const copyStart = Date.now();

  const sortedPackages = Array.from(requiredPackages).sort();
  const { copiedCount, fileStats } = copyPackagesSelectively(sortedPackages, ROOT_NODE_MODULES, OUT_NODE_MODULES);

  const copyElapsed = Date.now() - copyStart;
  console.log(`   ✅ 复制完成，耗时: ${copyElapsed}ms`);
  console.log(`   成功: ${copiedCount.success} 个包，失败: ${copiedCount.failed} 个`);
  console.log(`   硬链接: ${fileStats.hardLinks} 个文件，复制: ${fileStats.copies} 个文件\n`);

  const prunedDependencies = {};
  const allDeps = originalPackage.dependencies || {};
  const allDevDeps = originalPackage.devDependencies || {};

  for (const pkg of requiredPackages) {
    const version = allDeps[pkg] || allDevDeps[pkg] || actionPlugins[pkg];
    if (version) {
      prunedDependencies[pkg] = version;
    }
  }

  const prunedPackage = {
    name: originalPackage.name,
    version: originalPackage.version,
    private: true,
    dependencies: prunedDependencies,
    engines: originalPackage.engines
  };

  fs.writeFileSync(OUT_PACKAGE_JSON, JSON.stringify(prunedPackage, null, 2));

  const totalElapsed = Date.now() - totalStartTime;

  console.log('='.repeat(60));
  console.log('📊 智能裁剪统计:');
  console.log('='.repeat(60));
  console.log(`  需要的包数量:   ${requiredPackages.size}`);
  if (actionPluginNames.length > 0) {
    console.log(`  Action 插件:    ${actionPluginNames.length} 个`);
  }
  console.log(`  成功复制:       ${copiedCount.success} 个包`);
  console.log(`  失败:           ${copiedCount.failed} 个包`);
  console.log(`  硬链接文件:     ${fileStats.hardLinks} 个`);
  console.log(`  复制文件:       ${fileStats.copies} 个`);
  console.log(`  分析耗时:       ${analyzeElapsed}ms`);
  console.log(`  复制耗时:       ${copyElapsed}ms`);
  console.log(`  总耗时:         ${totalElapsed}ms`);
  console.log('='.repeat(60) + '\n');

  console.log('✅ 智能裁剪完成！');
  console.log(`📍 精简的 package.json 已保存到: ${OUT_PACKAGE_JSON}\n`);
}

smartPrune().catch(err => {
  console.error('❌ 智能裁剪失败:', err);
  process.exit(1);
});
